config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => "auth", :path_names => { :sign_in => "login", :sign_out => "logout" }, :controllers => { sessions: "sessions" }
  resources :users
  
  scope module: 'communal' do
  	resources :communal_services
  	resources :coldwaters
  	resources :hotwaters
  	resources :electrics
	end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/communal_service.rb
class CommunalService < ApplicationRecord

	has_many :electrics, dependent: :destroy
	has_many :hotwaters, dependent: :destroy
	has_many :coldwaters, dependent: :destroy

end

app/controllers/communal/coldwaters_controller.rb
class Communal::ColdwatersController < ApplicationController

  load_and_authorize_resource
  before_action :set_coldwater, only: [:show, :edit, :update, :destroy]

  # GET /coldwaters
  # GET /coldwaters.json
  def index
    @coldwaters = Coldwater.all
  end

  # GET /coldwaters/1
  # GET /coldwaters/1.json
  def show
  end

  # GET /coldwaters/new
  def new
    redirect_to communal_services_path if !params[:communal_service_id]
    @coldwater = Coldwater.new
    @coldwater.communal_service_id = params[:communal_service_id]
    @last_coldwater = Coldwater.last
    if @last_coldwater
      @coldwater.last_value = @last_coldwater.current_value
      @coldwater.price = @last_coldwater.price
    end
  end

  # GET /coldwaters/1/edit
  def edit
  end

  # POST /coldwaters
  # POST /coldwaters.json
  def create
    @coldwater = Coldwater.new(coldwater_params)

    respond_to do |format|
      if @coldwater.save
        format.html { redirect_to @coldwater, notice: 'Запись успешно добавлена.' }
        format.json { render :show, status: :created, location: @coldwater }
      else
        format.html { render :new }
        format.json { render json: @coldwater.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coldwaters/1
  # PATCH/PUT /coldwaters/1.json
  def update
    respond_to do |format|
      if @coldwater.update(coldwater_params)
        format.html { redirect_to @coldwater, notice: 'Запись успешно обновлена.' }
        format.json { render :show, status: :ok, location: @coldwater }
      else
        format.html { render :edit }
        format.json { render json: @coldwater.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coldwaters/1
  # DELETE /coldwaters/1.json
  def destroy
    @communal_service_id = @coldwater.communal_service.id
    @coldwater.destroy
    respond_to do |format|
      format.html { redirect_to communal_service_path(@communal_service_id), notice: 'Запись успешно удалена.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coldwater
      @coldwater = Coldwater.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coldwater_params
      params.require(:coldwater).permit(:last_value, :current_value, :price, :communal_service_id)
    end
end

app/controllers/communal/communal_services_controller.rb
class Communal::CommunalServicesController < ApplicationController

  load_and_authorize_resource
  before_action :set_communal_service, only: [:show, :edit, :update, :destroy]

  # GET /communal_services
  # GET /communal_services.json
  def index
    @communal_services = CommunalService.order(:end_period => 'DESC').paginate(:page => params[:page], :per_page => 10)
  end

  # GET /communal_services/1
  # GET /communal_services/1.json
  def show
    @electrics = @communal_service.electrics.all
    @hotwaters = @communal_service.hotwaters.all
    @coldwaters = @communal_service.coldwaters.all
    @electrics_sum = 0
    @hotwaters_sum = 0
    @coldwaters_sum = 0
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Оплата коммунальных услуг " + (l @communal_service.begin_period).to_s + "-" + (l @communal_service.end_period).to_s, encoding: "UTF-8", layout: "communal_pdf", page_size: "A4"
      end
    end
  end

  # GET /communal_services/new
  def new
    @communal_service = CommunalService.new
    @last_communal = CommunalService.order(:end_period => 'DESC').first
    if @last_communal
      @communal_service.begin_period = @last_communal.end_period
      @communal_service.end_period = @communal_service.begin_period + 1.month
    end
  end

  # GET /communal_services/1/edit
  def edit
  end

  # POST /communal_services
  # POST /communal_services.json
  def create
    @communal_service = CommunalService.new(communal_service_params)

    respond_to do |format|
      if @communal_service.save
        format.html { redirect_to @communal_service, notice: 'Период успешно добавлен.' }
        format.json { render :show, status: :created, location: @communal_service }
      else
        format.html { render :new }
        format.json { render json: @communal_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /communal_services/1
  # PATCH/PUT /communal_services/1.json
  def update
    respond_to do |format|
      if @communal_service.update(communal_service_params)
        format.html { redirect_to @communal_service, notice: 'Период успешно обновлен.' }
        format.json { render :show, status: :ok, location: @communal_service }
      else
        format.html { render :edit }
        format.json { render json: @communal_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /communal_services/1
  # DELETE /communal_services/1.json
  def destroy
    @communal_service.destroy
    respond_to do |format|
      format.html { redirect_to communal_services_url, notice: 'Период успешно удален.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_communal_service
      @communal_service = CommunalService.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def communal_service_params
      params.require(:communal_service).permit(:begin_period, :end_period)
    end
end

app/controllers/communal/electrics_controller.rb
class Communal::ElectricsController < ApplicationController

  load_and_authorize_resource
  before_action :set_electric, only: [:show, :edit, :update, :destroy]

  # GET /electrics
  # GET /electrics.json
  def index
    @electrics = Electric.all
  end

  # GET /electrics/1
  # GET /electrics/1.json
  def show
  end

  # GET /electrics/new
  def new
    redirect_to communal_services_path if !params[:communal_service_id]
    @electric = Electric.new
    @electric.communal_service_id = params[:communal_service_id]
    @last_electric = Electric.last
    if @last_electric
      @electric.last_value = @last_electric.current_value
      @electric.price = @last_electric.price
    end
  end

  # GET /electrics/1/edit
  def edit
  end

  # POST /electrics
  # POST /electrics.json
  def create
    @electric = Electric.new(electric_params)

    respond_to do |format|
      if @electric.save
        format.html { redirect_to @electric, notice: 'Запись успешно добавлена.' }
        format.json { render :show, status: :created, location: @electric }
      else
        format.html { render :new }
        format.json { render json: @electric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /electrics/1
  # PATCH/PUT /electrics/1.json
  def update
    respond_to do |format|
      if @electric.update(electric_params)
        format.html { redirect_to @electric, notice: 'Запись успешно обновлена.' }
        format.json { render :show, status: :ok, location: @electric }
      else
        format.html { render :edit }
        format.json { render json: @electric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /electrics/1
  # DELETE /electrics/1.json
  def destroy
    @communal_service_id = @electric.communal_service.id
    @electric.destroy
    respond_to do |format|
      format.html { redirect_to communal_service_path(@communal_service_id), notice: 'Запись успешно удалена.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_electric
      @electric = Electric.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def electric_params
      params.require(:electric).permit(:last_value, :current_value, :price, :communal_service_id)
    end
end

app/controllers/communal/hotwaters_controller.rb
class Communal::HotwatersController < ApplicationController

  load_and_authorize_resource
  before_action :set_hotwater, only: [:show, :edit, :update, :destroy]

  # GET /hotwaters
  # GET /hotwaters.json
  def index
    @hotwaters = Hotwater.all
  end

  # GET /hotwaters/1
  # GET /hotwaters/1.json
  def show
  end

  # GET /hotwaters/new
  def new
    redirect_to communal_services_path if !params[:communal_service_id]
    @hotwater = Hotwater.new
    @hotwater.communal_service_id = params[:communal_service_id]
    @last_hotwater = Hotwater.last
    if @last_hotwater
      @hotwater.last_value = @last_hotwater.current_value
      @hotwater.price = @last_hotwater.price
    end
  end

  # GET /hotwaters/1/edit
  def edit
  end

  # POST /hotwaters
  # POST /hotwaters.json
  def create
    @hotwater = Hotwater.new(hotwater_params)

    respond_to do |format|
      if @hotwater.save
        format.html { redirect_to @hotwater, notice: 'Запись успешно добавлена.' }
        format.json { render :show, status: :created, location: @hotwater }
      else
        format.html { render :new }
        format.json { render json: @hotwater.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotwaters/1
  # PATCH/PUT /hotwaters/1.json
  def update
    respond_to do |format|
      if @hotwater.update(hotwater_params)
        format.html { redirect_to @hotwater, notice: 'Запись успешно обновлена.' }
        format.json { render :show, status: :ok, location: @hotwater }
      else
        format.html { render :edit }
        format.json { render json: @hotwater.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotwaters/1
  # DELETE /hotwaters/1.json
  def destroy
    @communal_service_id = @hotwater.communal_service.id
    @hotwater.destroy
    respond_to do |format|
      format.html { redirect_to communal_service_path(@communal_service_id), notice: 'Запись успешно удалена.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotwater
      @hotwater = Hotwater.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotwater_params
      params.require(:hotwater).permit(:last_value, :current_value, :price, :communal_service_id)
    end
end

app/helpers/communal/coldwaters_helper.rb
module Communal::ColdwatersHelper
end

app/helpers/communal/communal_services_helper.rb
module Communal::CommunalServicesHelper

	def show_price(price)
    number_to_currency(price, :precision => 2, :unit => "руб.", :delimiter => " ", :separator => ".", :format => "%n %u")
  end

  def make_currency(currency)
    number_to_currency(currency, :precision => 2, :delimiter => "", :separator => ".", :format => "%n")
  end


  def make_table_pdf
  	
  	@last_values = ""
  	@current_values = ""
  	@prices = ""
  	@consumption = ""
  	@cost = ""
  	@cost_sum_html = ""
  	@rowspan = 1
  	@result = 0

  	@colspan_ehc = [ (@communal_service.electrics.count if @communal_service.electrics.count > 0) || 1, (@communal_service.hotwaters.count if @communal_service.hotwaters.count >0) || 1, (@communal_service.coldwaters.count if @communal_service.coldwaters.count > 0) || 1 ]

  	@colspan_ehc.each do |v|
  		if v > 1
  			@rowspan = 2
  		end
  	end

    def make_column(items)
      @cost_sum = 0
      if items.any?
        items.each do |item|
          @last_values += ("<td>" + item.last_value.to_s + "</td>")
  		    @current_values += ("<td>" + item.current_value.to_s + "</td>")
  		    @consumption += ("<td>" + (item.current_value - item.last_value).to_s + "</td>")
  		    @prices += ("<td>" + make_currency(item.price).to_s + "</td>")
  		    @cost += ("<td>" + make_currency((item.current_value - item.last_value) * item.price).to_s + "</td>")
  		    @cost_sum += (item.current_value - item.last_value) * item.price
        end
      else
        @last_values += ("<td></td>")
        @current_values += ("<td></td>")
        @consumption += ("<td></td>")
        @prices += ("<td></td>")
        @cost += ("<td></td>")
      end

      @result += @cost_sum
    end

    make_column(@communal_service.electrics)
    @cost_sum_html += ("<td class='after_rowspan' colspan='" + @colspan_ehc[0].to_s + "'>" + make_currency(@cost_sum).to_s + "</td>")
    make_column(@communal_service.hotwaters)
    @cost_sum_html += ("<td colspan='" + @colspan_ehc[1].to_s + "'>" + make_currency(@cost_sum).to_s + "</td>")
    make_column(@communal_service.coldwaters)
    @cost_sum_html += ("<td colspan='" + @colspan_ehc[2].to_s + "'>" + make_currency(@cost_sum).to_s + "</td>")

  	return @last_values, @current_values, @consumption, @prices, @cost, @cost_sum_html, @result, @colspan_ehc, @rowspan
  end
	
end

app/helpers/communal/electrics_helper.rb
module Communal::ElectricsHelper
end

app/helpers/communal/hotwaters_helper.rb
module Communal::HotwatersHelper
end

app/views/communal/communal_services/_form.html.erb
<%= form_for @communal_service, :html => { :class => "form-horizontal communal_service" } do |f| %>

  <% if @communal_service.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@communal_service.errors.count, "error") %> prohibited this communal_service from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @communal_service.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :begin_period, :value => "Начало периода", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_select :begin_period, :class => 'form-control' %>
    </div>
    <%=f.error_span(:begin_period) %>
  </div>

  <div class="form-group">
    <%= f.label :end_period, :value => "Конец периода", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_select :end_period, :class => 'form-control' %>
    </div>
    <%=f.error_span(:end_period) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Сохранить", :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                communal_services_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/communal/communal_services/edit.html.erb
<%- model_class = CommunalService -%>
<% content_for :title, "Коммунальные услуги" %>

<div class="page-header">
  <h1>Редактирование периода</h1>
</div>
<%= render :partial => 'form' %>

app/views/communal/communal_services/index.html.erb
<%- model_class = CommunalService -%>
<% content_for :title, "Коммунальные услуги" %>

<div class="page-header">
  <h1>Коммунальные услуги</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Период</th>
      <th>Сумма</th>
      <th>PDF</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @communal_services.each do |communal_service| %>
      <tr>
        <td><%= link_to (l communal_service.begin_period).to_s + " - " + (l communal_service.end_period).to_s, communal_service_path(communal_service) %></td>
        <td><%= show_price(communal_service.amount) %></td>
        <td><%= link_to "PDF", communal_service_path(communal_service, format: :pdf), :class => "btn btn-default btn-xs" %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_communal_service_path(communal_service), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      communal_service_path(communal_service),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="digg_pagination">
  <%= will_paginate @communal_services, :container => false %>
</div>

<br />

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_communal_service_path,
            :class => 'btn btn-primary' %>

app/views/communal/communal_services/new.html.erb
<%- model_class = CommunalService -%>
<% content_for :title, "Коммунальные услуги" %>

<div class="page-header">
  <h1>Создание нового периода</h1>
</div>
<%= render :partial => 'form' %>

app/views/communal/communal_services/show.html.erb
<%- model_class = CommunalService -%>
<% content_for :title, "Коммунальные услуги" %>

<div class="page-header">
  <h1><%= (l @communal_service.begin_period).to_s + " - " + (l @communal_service.end_period).to_s %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Начало периода:</strong></dt>
  <dd><%=l @communal_service.begin_period %></dd>
  <dt><strong>Конец периода:</strong></dt>
  <dd><%=l @communal_service.end_period %></dd>
</dl>

<br />
<br />

<div class="container-fluid">

<%= link_to t('.back', :default => t("helpers.links.back")),
              communal_services_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_communal_service_path(@communal_service), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              communal_service_path(@communal_service),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<div class="pull-right">
<%= link_to "PDF", communal_service_path(@communal_service, format: :pdf), :class => "btn btn-default" %>
</div>
</div>

<br />
<br />

<div id="electric" class="col-md-12 well">
<h2>Электричество</h2>
<% if @electrics.any? %>
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Предыдущиее, кВт</th>
      <th>Текущее, кВт</th>
      <th>Расход, кВт</th>
      <th>Тариф, руб.</th>
      <th>Сумма, руб.</th>
      <th>Действие</th>
    </tr>
  </thead>
  <tbody>
    <% @electrics.each do |electric| %>
      <% @electric_result = (electric.current_value - electric.last_value) * electric.price %>
      <% @electrics_sum += @electric_result %>
      <tr>
        <td><%= electric.last_value %></td>
        <td><%= electric.current_value %></td>
        <td><%= electric.current_value - electric.last_value %></td>
        <td><%= make_currency(electric.price) %></td>
        <td><%= make_currency(@electric_result) %></td>
        <td>
          <%= link_to "Просмотр", electric_path(electric), :class => 'btn btn-xs btn-default' %>
          <%= link_to "Удалить", electric_path(electric), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
    <tr>
      <td></td><td></td><td></td>
      <td>Итог:</td>
      <td><%= make_currency(@electrics_sum) %></td>
      <td></td>
    </tr>
  </tbody>
</table>
<% end %>
<%= link_to "Добавить", new_electric_path(:communal_service_id => @communal_service.id), :class => "btn btn-xs btn-primary" %>
</div>

<br />
<br />

<div id="hotwater" class="col-md-12 well">
  <h2>Горячая вода</h2>
<% if @hotwaters.any? %>
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Предыдущиее, м3</th>
      <th>Текущее, м3</th>
      <th>Расход, м3</th>
      <th>Тариф, руб.</th>
      <th>Сумма, руб.</th>
      <th>Действие</th>
    </tr>
  </thead>
  <tbody>
    <% @hotwaters.each do |hotwater| %>
      <% @hotwater_result = (hotwater.current_value - hotwater.last_value) * hotwater.price %>
      <% @hotwaters_sum += @hotwater_result %>
      <tr>
        <td><%= hotwater.last_value %></td>
        <td><%= hotwater.current_value %></td>
        <td><%= hotwater.current_value - hotwater.last_value %></td>
        <td><%= make_currency(hotwater.price) %></td>
        <td><%= make_currency(@hotwater_result) %></td>
        <td>
          <%= link_to "Просмотр", hotwater_path(hotwater), :class => 'btn btn-xs btn-default' %>
          <%= link_to "Удалить", hotwater_path(hotwater), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
    <tr>
      <td></td><td></td><td></td>
      <td>Итог:</td>
      <td><%= make_currency(@hotwaters_sum) %></td>
    </tr>
  </tbody>
</table>
<% end %>
<%= link_to "Добавить", new_hotwater_path(:communal_service_id => @communal_service.id), :class => "btn btn-xs btn-primary" %>
</div>

<br />
<br />

<div id="coldwater" class="col-md-12 well">
  <h2>Холодная вода</h2>
<% if @coldwaters.any? %>
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Предыдущиее, м3</th>
      <th>Текущее, м3</th>
      <th>Расход, м3</th>
      <th>Тариф, руб.</th>
      <th>Сумма, руб.</th>
      <th>Действие</th>
    </tr>
  </thead>
  <tbody>
    <% @coldwaters.each do |coldwater| %>
      <% @coldwater_result = (coldwater.current_value - coldwater.last_value) * coldwater.price %>
      <% @coldwaters_sum += @coldwater_result %>
      <tr>
        <td><%= coldwater.last_value %></td>
        <td><%= coldwater.current_value %></td>
        <td><%= coldwater.current_value - coldwater.last_value %></td>
        <td><%= make_currency(coldwater.price) %></td>
        <td><%= make_currency(@coldwater_result)  %></td>
        <td>
        <%= link_to "Просмотр", coldwater_path(coldwater), :class => 'btn btn-xs btn-default' %>
          <%= link_to "Удалить", coldwater_path(coldwater), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
    <tr>
      <td></td><td></td><td></td>
      <td>Итог:</td>
      <td><%= make_currency(@coldwaters_sum) %></td>
    </tr>
  </tbody>
</table>
<% end %>
<%= link_to "Добавить", new_coldwater_path(:communal_service_id => @communal_service.id), :class => "btn btn-xs btn-primary" %>
</div>

<br />
<br />

<div id="final_sum" class="col-md-12">
  <h2>Результат</h2>
  <table class="table table-striped">
  <tbody>
    <tr>
      <td>Итог:</td>
      <td><%= show_price(@electrics_sum + @hotwaters_sum + @coldwaters_sum) %></td>
    </tr>
  </tbody>
  </table>
</div>

<br />
<br />

<div class="container-fluid">

<%= link_to t('.back', :default => t("helpers.links.back")),
              communal_services_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_communal_service_path(@communal_service), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              communal_service_path(@communal_service),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<div class="pull-right">
<%= link_to "PDF", communal_service_path(@communal_service, format: :pdf), :class => "btn btn-default" %>
</div>

</div>

app/views/communal/communal_services/show.pdf.erb
<div>
<br />
<span style="text-align: center;"><h3>Электричество, ГВС, ХВС</h3></span>
<p style="text-align: center; margin-top: 60px;"><%= (l @communal_service.begin_period).to_s + " - " + (l @communal_service.end_period).to_s %></p>
<br />
<br />

<% @last_values, @current_values, @consumption, @prices, @cost, @cost_sum_html, @result, @colspan_ehc, @rowspan = make_table_pdf %>

<table class="table_communal_pdf">
	<thead>
		<th class="td_first_col"></th>
		<th colspan="<%= @colspan_ehc[0] %>">Электричество</th>
		<th colspan="<%= @colspan_ehc[1] %>">ГВС</th>
		<th colspan="<%= @colspan_ehc[2] %>">ХВС</th>
	</thead>
	<tbody>
		<tr>
			<td class="td_first_col">Предыдущие показания</td>
			<%=raw @last_values %>
		</tr>
		<tr>
			<td class="td_first_col">Текущие показания</td>
			<%=raw @current_values %>
		</tr>
		<tr>
			<td class="td_first_col">Расход</td>
			<%=raw @consumption %>
		</tr>
		<tr>
			<td class="td_first_col"></td>
			<td colspan="<%= @colspan_ehc[0] %>"></td>
			<td colspan="<%= @colspan_ehc[1] %>"></td>
			<td colspan="<%= @colspan_ehc[2] %>"></td>
		</tr>
		<tr>
			<td class="td_first_col">Тарифы, руб.</td>
			<%=raw @prices %>
		</tr>
		<tr>
			<td class="td_first_col"></td>
			<td colspan="<%= @colspan_ehc[0] %>"></td>
			<td colspan="<%= @colspan_ehc[1] %>"></td>
			<td colspan="<%= @colspan_ehc[2] %>"></td>
		</tr>
		<tr>
			<td  class="td_first_col" rowspan="<%= @rowspan %>">Расход, руб.</td>
			<%=raw @cost %>
		</tr>
		<% if @rowspan > 1 %>
			<tr>
				<%=raw @cost_sum_html %>
			</tr>
		<% end %>
	</tbody>
</table>

<br />
<br />
<br />
<table class="table_communal_result_pdf">
	<tr>
		<td class="td_first_col"><b>ИТОГ:</b></td>
		<td><b><%= show_price(@result) %></b></td>
	</tr>
</table>
</div>